org.slf4j.simpleLogger.defaultLogLevel=warn
org.slf4j.simpleLogger.log.org.mongodb=off
org.slf4j.simpleLogger.log.org.mongodb.driver=off
org.slf4j.simpleLogger.log.com.mongodb=off
org.slf4j.simpleLogger.log.com.mongodb.driver=off
org.slf4j.simpleLogger.log.loyfael.libs.mongodb=off
org.slf4j.simpleLogger.log.loyfael.libs.mongodb.driver=off
